export const countryCodes = [
  { code: "+970", label: "PS +970", country: "Palestine" },
  { code: "+972", label: "IL +972", country: "Israel" },
  { code: "+962", label: "JO +962", country: "Jordan" },
  { code: "+961", label: "LB +961", country: "Lebanon" },
  { code: "+963", label: "SY +963", country: "Syria" },
  { code: "+20",  label: "EG +20",  country: "Egypt" },
  { code: "+966", label: "SA +966", country: "Saudi Arabia" },
  { code: "+971", label: "AE +971", country: "UAE" },
  { code: "+965", label: "KW +965", country: "Kuwait" },
  { code: "+974", label: "QA +974", country: "Qatar" },
  { code: "+968", label: "OM +968", country: "Oman" },
  { code: "+973", label: "BH +973", country: "Bahrain" },
  { code: "+964", label: "IQ +964", country: "Iraq" },
  { code: "+967", label: "YE +967", country: "Yemen" },
  { code: "+216", label: "TN +216", country: "Tunisia" },
  { code: "+212", label: "MA +212", country: "Morocco" },
  { code: "+213", label: "DZ +213", country: "Algeria" },
  { code: "+218", label: "LY +218", country: "Libya" },
  { code: "+249", label: "SD +249", country: "Sudan" },
  { code: "+1",   label: "US +1",   country: "United States" },
  { code: "+44",  label: "GB +44",  country: "United Kingdom" },
  { code: "+49",  label: "DE +49",  country: "Germany" },
  { code: "+33",  label: "FR +33",  country: "France" },
  { code: "+90",  label: "TR +90",  country: "Turkey" },
  { code: "+91",  label: "IN +91",  country: "India" },
  { code: "+86",  label: "CN +86",  country: "China" },
  { code: "+7",   label: "RU +7",   country: "Russia" },
];